name: Update Prayer Times

on:
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install requests pytz
      - run: python scripts/generate.py
      - run: |
          git config --global user.name "PrayerBot"
          git config --global user.email "bot@example.com"
          git add .
          git commit -m "Update" || echo "No changes"
          git push
